sudo: false
language: node_js
node_js: 8
install: yarn
before_deploy: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: vr/build
  on:
    branch: master